### ISSUE TITLE
pkasolver-GPU issue at high scale protonation

### ISSUE THREAD

**Issue by Feriolet** [ci-lab-cz/easydock#35]
I am not sure if I should try asking this at the pkasolver repo instead, but I was hoping that maybe this issue can be solved here.

I am trying to dock 600k molecules for almost a week, but I am stuck on the protonation step with pkasolver. I am currently using GPU because it is significantly faster than using CPU by 10x in my case. However, I keep getting stuck with the warning message and a sudden termination.

```
/home/user/miniforge3/envs/easydock_gpu/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

I tried print debugging to see which code it specifically terminate, but unfortunately I do not get any more information beyond that.

```python
def protonate_pkasolver(input_fname: str, output_fname: str, ncpu: int = 1, dock_ncpu: int=1):
    
    with open(input_fname,'r') as input_file:
        smi_l = input_file.readlines()

    # Assuming that using 25000 compound per loop will avoid the GPU RAM Error (Semparhore leakage and out of memory error)
    chunk_number = ceil(len(smi_l)/25000)
    chunk_smi_l = chunk_into_n(smi_l, chunk_number)

    temp_fname_list = []
    for chunk in chunk_smi_l:
        with tempfile.NamedTemporaryFile(suffix='.smi', mode='w', encoding='utf-8', delete=False) as input_tmp:
            input_tmp.write(''.join(chunk))
            output_tmp = tempfile.NamedTemporaryFile(suffix='.smi', mode='w', encoding='utf-8', delete=False)
            temp_fname_list.append((input_tmp.name, output_tmp.name))

    from pkasolver.query import QueryModel
    model = QueryModel()
    
    for input_f, output_f in temp_fname_list:
        print(f"Output file {output_f} from {input_f}")
    #using maxtasksperchild=10 and chunksize=10 means that each GPU worker will be replaced after doing 100 molecules (new PID)
    #in other words, the worker are allowed to do 10 tasks, with each tasks having to protonate 10 molecules.
    #this is done because I suspect the CUDA out of memory Error is due to the worker having to protonate #num_compound/gpu_threads without being replaced,
    #which cause the memory leak.
    #https://github.com/pytorch/pytorch/issues/44156
        pool = mp.get_context('spawn').Pool(20, maxtasksperchild=10)
        with open(output_f, 'wt') as f:
            for smi, name in pool.imap_unordered(partial(__protonate_pkasolver, model=model), read_input(input_f), chunksize=10):
                f.write(f'{smi}\t{name}\n')

        pool.close()
        pool.join()
    print(f'writing actual content to {output_fname} from {input_fname}')
    with open(output_fname, 'wt') as output_file:
        for temp_fname in temp_fname_list:
            input_temp_fname, output_temp_fname = temp_fname

            with open(output_temp_fname,'r') as output_smi:
                output_file.write(''.join(output_smi))
                output_smi.seek(0,0)
                print(f"{output_temp_fname} has {len(output_smi.readlines())}")
            print('removing file...')
            os.remove(input_temp_fname)
            os.remove(output_temp_fname)
            print('removing file is done')
```

Here is the output that I get:
```
Output file /tmp/tmppbb8kr9v.smi from /tmp/tmp3ypkg8g6.smi
Output file /tmp/tmpzre3vlxp.smi from /tmp/tmpriot8o4b.smi
Output file /tmp/tmplmqr6i4a.smi from /tmp/tmpk1xplaiu.smi
Output file /tmp/tmplp9lpagp.smi from /tmp/tmpf3ud4ma5.smi
Output file /tmp/tmpnru5ewr7.smi from /tmp/tmphe0l4ud5.smi
Output file /tmp/tmpv_lm44q7.smi from /tmp/tmpr77d0p1d.smi
Output file /tmp/tmpvdive5d0.smi from /tmp/tmpy29nuqvr.smi
Output file /tmp/tmpracf5f6m.smi from /tmp/tmpdgjt6y3p.smi
Output file /tmp/tmpcy_vj5j7.smi from /tmp/tmpdbxwh340.smi
Output file /tmp/tmpi95qdgza.smi from /tmp/tmp58lse777.smi
Output file /tmp/tmpvv2z3wnk.smi from /tmp/tmp_qtepbfn.smi
Output file /tmp/tmp537lkrwj.smi from /tmp/tmpiouw2wnq.smi
Output file /tmp/tmpb_8waiba.smi from /tmp/tmp53lkpoxq.smi
Output file /tmp/tmpkspme0_t.smi from /tmp/tmp5l7hlpkv.smi
Output file /tmp/tmprsuep50_.smi from /tmp/tmp2trllacy.smi
Output file /tmp/tmphn_5dpgx.smi from /tmp/tmp53zii_e9.smi
Output file /tmp/tmpi1f40gu3.smi from /tmp/tmp42dfrmet.smi
Output file /tmp/tmpqwvjz8f1.smi from /tmp/tmpk2g8yssc.smi
Output file /tmp/tmpqcpuhwx0.smi from /tmp/tmp7pgv2yvt.smi
Output file /tmp/tmpdb2q5yef.smi from /tmp/tmp0x73hz0y.smi
Output file /tmp/tmpkomy499p.smi from /tmp/tmpmdqb6snw.smi
Output file /tmp/tmp768qr0ag.smi from /tmp/tmp2srprmwb.smi
Output file /tmp/tmpx0qq1fyk.smi from /tmp/tmp0kxxtgaw.smi
Output file /tmp/tmp6hz61r22.smi from /tmp/tmp4occm7n1.smi
/home/user/miniforge3/envs/easydock_gpu/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Surprisingly, the input and output files from `chunk_into_n` functions do not exist anymore even when it does not reach the `os.remove(file)` I assume, which is very odd. 

As can be seen in the modified `protonate_pkasolver()` function, I am using 20 GPU threads from 1 GPU, which consumes almost 20 GB of memory. If it truly is a memory issue, I was wondering if there is a way to avoid that while still using `torch.multiprocessing` to protonate the molecule.

**Comment by DrrDom** [comment]
In your case it is unnecessary to create temporary output files, and the code can be simplified

```python
temp_fname_list = []
for chunk in chunk_smi_l:
    with tempfile.NamedTemporaryFile(suffix='.smi', mode='w', encoding='utf-8', delete=False) as input_tmp:
        input_tmp.write(''.join(chunk))
        temp_fname_list.append(input_tmp.name)

from pkasolver.query import QueryModel

model = QueryModel()

for input_f in temp_fname_list:
    with mp.get_context('spawn').Pool(20, maxtasksperchild=10) as pool:
        with open(output_fname, 'wt') as f:
            for smi, name in pool.imap_unordered(partial(__protonate_pkasolver, 
                                                         model=model), 
                                                 read_input(input_f),
                                                 chunksize=10):
                f.write(f'{smi}\t{name}\n')

for temp_fname in temp_fname_list:
    os.remove(temp_fname)
```

Maybe this simplification will allow to easier locate the source of the issue. To provide more information you may return from `__protonate_pkasolver` a process ID and save it along SMILES in the output file to check later how many molecules were processed by each process. Maybe add as an output of `__protonate_pkasolver` the memory consumption by each process or a whole program for each molecule processing and append to the output file, in this way you may see how quickly it accumulates and whether it drops down or not.

What happen if you set `maxtasksperchild` to 1? Did it help to avoid memory issue? This may kill the performance, but at least we will know that this works.

Disappearing of temporary files is really very odd and I cannot guess why it may happen.

**Comment by Feriolet** [comment]
Do you think this is enough? I am not sure if this code will calculate the entire memory consumed by the PID.

```python
def __protonate_pkasolver():
    #pkasolver calculation
    pid = os.getpid()
    python_process = psutil.Process(pid)
    memoryUse = python_process.memory_info()[0]/2.**30
    print(f'{mol_name}, {pid} memory used: {memoryUse}', flush=True)
    return Chem.MolToSmiles(output_mol), mol_name

**Comment by DrrDom** [comment]
This should work for RAM, but if you have an issue with GPU memory there should be some way to to get its size specifically.

**Comment by Feriolet** [comment]
I found the way to get the memory by `nvtop` module

```python
def __protonate_pkasolver():
    pid = os.getpid()
    python_process = psutil.Process(pid)
    memoryUse = python_process.memory_info()[0]/2.**30
    gpu_process = Device(0).processes()[pid].gpu_memory_human()
    print(f'{mol_name}, {pid} RAM: {memoryUse} GB, GPU: {gpu_process}', flush=True)
    return Chem.MolToSmiles(output_mol), mol_name
```

which has the GPU input match with the `nvidia-smi` (848 MB per PID)
```
Z2385375444_1, 492933 RAM: 2.4158058166503906 GB, GPU: 848.0MiB
Z2053097792_0, 493197 RAM: 2.4227828979492188 GB, GPU: 846.0MiB
Z1530931124_1, 493609 RAM: 2.4175071716308594 GB, GPU: 848.0MiB
Z1530931124_0, 493197 RAM: 2.4227828979492188 GB, GPU: 846.0MiB
Z2053731410_1, 492294 RAM: 2.419513702392578 GB, GPU: 846.0MiB
Z1646243494_0, 493609 RAM: 2.4180450439453125 GB, GPU: 848.0MiB
Z1456199107_0, 492567 RAM: 2.4231224060058594 GB, GPU: 846.0MiB
Z2229075231_0, 492294 RAM: 2.4195175170898438 GB, GPU: 846.0MiB
Z1802720758_0, 493738 RAM: 2.4240989685058594 GB, GPU: 848.0MiB
Z1839751615_2, 493870 RAM: 2.418170928955078 GB, GPU: 846.0MiB
Z1839751615_3, 493870 RAM: 2.4184837341308594 GB, GPU: 846.0MiB
Z1994985802_0, 492933 RAM: 2.4158096313476562 GB, GPU: 848.0MiB
```

**Comment by DrrDom** [comment]
Could you locate a memory leak? Did it remain after `maxtasksperchild=1`?

**Comment by Feriolet** [comment]
omg it works now. Yes, I guess using `maxtasksperchild=1` solve the issue. I tried to raise the `chunk_size=20` from 10 to compensate the performance, and it does not create the issue anymore. It is currently at the docking stage now!

**Comment by DrrDom** [comment]
Good to know!
If it works it may be reasonable to commit this fix to the repo to enable a GPU support.
Maybe the chunk size can be increased even more, if the model processes molecules fast.

> I guess opening the `output_fname` first before making the `for` loop would be a better choice.

Yes, I agree, it will be better.

**Comment by Feriolet** [comment]
Yep, we can make a commit to enable a GPU support. However, my issues are:
1. Is it possible to switch GPU and CPU freely? Correct me if I'm wrong, but I worried that if I have torch-gpu package, I could not ask it to only use CPU. Do we have to modify the pkasolver source code to use CPU when asked (even if we have GPU) directly? I don't want to use GPU when I have very few SMILES to dock because it caused CUDA Warning (it will still dock, but having my terminal filled with hundreds/thousands of these warning is annoying sometimes). My workaround way for now is to have a separate conda environment `easydock` for CPU and `easydock_gpu` for GPU protonation.
2. To detect the GPU, we would have to pass the `ngpu` argument similar to `ncpu` argument, right?

Not related to GPU, but is it possible to have an rdkit check on the protonated smiles for pkasolver before returning from the `add_protonation(mol)` function? If I'm not wrong, pkasolver only return the first SMILES/mol that has pKa > pH and disregard the rest. It's not really important since only a small proportion of the library did not get docked because of it, but I guess it is a "nice to have", given that my assumption is correct.

**Comment by Feriolet** [comment]
Apparently the CUDA Warning is given when the protonation and docking is run without termination. I have not tried with larger dataset yet, but if I protonate and dock on separate command, the warning does not occur. This is the Warning btw:

```
[W CudaIPCTypes.cpp:95] Producer process tried to deallocate over 1000 memory blocks referred by consumer processes. Deallocation might be significantly slowed down. We assume it will never going to be the case, but if it is, please file but to https://github.com/pytorch/pytorch
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
...
...
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
```

**Comment by DrrDom** [comment]
> Yep, we can make a commit to enable a GPU support. However, my issues are:
> 
>  1. Is it possible to switch GPU and CPU freely? Correct me if I'm wrong, but I worried that if I have torch-gpu package, I could not ask it to only use CPU. Do we have to modify the pkasolver source code to use CPU when asked (even if we have GPU) directly? I don't want to use GPU when I have very few SMILES to dock because it caused CUDA Warning (it will still dock, but having my terminal filled with hundreds/thousands of these warning is annoying sometimes). My workaround way for now is to have a separate conda environment `easydock` for CPU and `easydock_gpu` for GPU protonation.
> 
>  2. To detect the GPU, we would have to pass the `ngpu` argument similar to `ncpu` argument, right?
> 


Not an easy question for me, because I'm not familiar with GPU support in Python and torch. This should be investigated whether it is possible to switch between CPU and GPU modes through API. If so, then we can introduce an additional `ngpu` argument, which will be `None` by default and which can be set by a user independently on `ncpu`.

> Not related to GPU, but is it possible to have an rdkit check on the protonated smiles for pkasolver before returning from the `add_protonation(mol)` function? If I'm not wrong, pkasolver only return the first SMILES/mol that has pKa > pH and disregard the rest. It's not really important since only a small proportion of the library did not get docked because of it, but I guess it is a "nice to have", given that my assumption is correct.

I did not fully understand the issue. What kind check do you propose - validity of SMILES or presence of SMILES? pkasolver creates a sequence of forms ranked by their pKa. Each form has two states - protonated and deprotonated. Currently the function returns a protonated state of a form which has pKa > pH, otherwise it returns a deprotonated state of the first form.

However, there were strange protonated forms like protonated amide groups, which are fixed before return the output. If there are some other typical errors, we may create a list of patterns to check all of them and fix.

**Comment by DrrDom** [comment]
What did you mean protonate and dock on separate command?

I now experience the issue with database initialization, which takes too long for small datasets (<10000). I expect that this was mainly caused by our recent implementation of stereoisomers enumeration which may take too much time for some compounds. Therefore, I started to think to introduce an argument `--init_only` to execute only database initialization and protonation steps. And afterwards a user may remove this argument to run actual docking. This will save resources if several servers are used for docking and they are idle waiting for these preliminary steps, thus, wasting the computational time. However, this implementation may require the revision of how arguments are stored in a database - not an easy task.

**Comment by Feriolet** [comment]
> What did you mean protonate and dock on separate command?

After I protonate, I terminated the `run_dock` command and rerun it again, because it will skip the protonation process and immediately start the docking process. I think that the error occur when the CUDA, which is still there even after `pool` is done, is exposed to the new `pool` by docking. I tried to use another `multiprocessing` package by `ray` package, and it does not give the error anymore. However, it gives a new warning (which may be silenced/ignored by some command)

```python
from ray.util import multiprocessing
def protonate_pkasolver(input_fname: str, output_fname: str, ncpu: int = 1, dock_ncpu: int=1):

    with open(input_fname,'r') as input_file:
        smi_l = input_file.readlines()

    # We predict that using 50000 compound per loop will avoid the GPU RAM Error (Semparhore leakage and out of memory error)
    chunk_number = ceil(len(smi_l)/50000)
    chunk_smi_l = chunk_into_n(smi_l, chunk_number)

    temp_fname_list = []
    for chunk in chunk_smi_l:
        with tempfile.NamedTemporaryFile(suffix='.smi', mode='w', encoding='utf-8', delete=False) as input_tmp:
            input_tmp.write(''.join(chunk))
            temp_fname_list.append(input_tmp.name)

    from pkasolver.query import QueryModel
    model = QueryModel()
    #logger = logging.getLogger()
    with open(output_fname, 'wt') as f:
        for input_f in temp_fname_list:
            #using maxtasksperchild=1 and chunksize=50 means that each GPU worker will be replaced after doing 50 molecules (new PID)
            #in other words, the worker are allowed to do 1 tasks, with each tasks having to protonate 50 molecules.
            #this is done because I suspect the CUDA out of memory Error is due to the worker having to protonate #num_compound/gpu_threads without being replaced,
            #which cause the memory leak.
            #Both chunksize and maxtasksperchild are important. maxtasksperchild=1 seems to resolve the issue,
            #so DO NOT change this value unless you have a strong justification. chunksize can be modified, but I highly discouraged it,
            #because maxtasksperchild kind of reduces the performance moderately. You can try to increase the chunksize if you want to test it.
            #https://github.com/pytorch/pytorch/issues/44156
            with multiprocessing.Pool(10, maxtasksperchild=1, ray_remote_args={"num_gpus": 1/10}) as pool:
                    for smi, name in pool.imap_unordered(partial(__protonate_pkasolver, 
                                                                model=model), 
                                                        read_input(input_f),
                                                        chunksize=50):
                        f.write(f'{smi}\t{name}\n')
        
    for temp_fname in temp_fname_list:
        os.remove(temp_fname)
```

```
2024-05-21 15:57:20,030	INFO worker.py:1749 -- Started a local Ray instance.
EASYDOCK ERROR: ZINC001436309987_1_0, smiles CO[C@H]1CC[NH](C(=O)CCCN(C)C2=NS(=O)(=O)c3ccccc32)CC1(C)C obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436289659_1_0, smiles COc1cc(C(=O)[NH]2CCS(=O)(=O)C[C@H]2C2CC2)ccc1OCc1cscn1 obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436289660_1_0, smiles COc1cc(C(=O)[NH]2CCS(=O)(=O)C[C@@H]2C2CC2)ccc1OCc1cscn1 obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436290646_1_0, smiles O=C(c1cc(Br)c2c(c1)OCO2)N1CC(=O)[NH](CCC(F)(F)F)C1 obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436290695_1_0, smiles Cc1ccc(C)c(N2N=C(C(=O)[NH]3CC(=O)[NH](CCC(F)(F)F)C3)CCC2=O)c1 obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436291075_1_0, smiles O=C(c1cn2c(Br)cnc2s1)N1CC(=O)[NH](CCC(F)(F)F)C1 obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436302816_1_0, smiles Cc1nnsc1COC(=O)C1CC[NH](S(=O)(=O)c2ccc3c(c2)CCC3)CC1 obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436288223_1_0, smiles O=C1C[NH](C(=O)c2nc(Br)c3ccccn23)C[NH]1CCC(F)(F)F obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436289494_1_0, smiles Cc1c(C(=O)N2CC(=O)[NH](CCC(F)(F)F)C2)nnn1-c1cccc(Cl)c1 obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436291635_1_0, smiles CS(=O)(=O)Cc1c(C(=O)N2CC(=O)[NH](CCC(F)(F)F)C2)oc2ccccc12 obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436291637_1_0, smiles O=C1CN(C(=O)[C@H]2CC[NH](C(=O)OCc3ccccc3)C2)CN1CCC(F)(F)F obtained after protonation could not be read by RDKit. The molecule was skipped.
EASYDOCK ERROR: ZINC001436291641_1_0, smiles O=C1CN(C(=O)[C@@H]2CC[NH](C(=O)OCc3ccccc3)C2)CN1CCC(F)(F)F obtained after protonation could not be read by RDKit. The molecule was skipped.
[36m(autoscaler +30s)[0m Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
[33m(autoscaler +30s)[0m Warning: The following resource request cannot be scheduled right now: {'GPU': 0.1}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[33m(autoscaler +1m5s)[0m Warning: The following resource request cannot be scheduled right now: {'GPU': 0.1}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
protonation done in 77.19s
```

**Comment by Feriolet** [comment]
For the `--init` process, I notice that the compound is initialized very slowly a long time ago because some molecules take a long time to generate the isomers. That's why to speed up the process, I tend to multiply the ncpu needed with the cpu in the `config.yml` for docking (I hardcoded it since I don't want to add up more argument to `--init_db` at that time), which speeds up the process in linear fashion if I remembered (it takes around 3 hours to initialize ~600k compound including isomers with 150 CPU).

**Comment by Feriolet** [comment]
> I did not fully understand the issue. What kind check do you propose - validity of SMILES or presence of SMILES? pkasolver creates a sequence of forms ranked by their pKa. Each form has two states - protonated and deprotonated. Currently the function returns a protonated state of a form which has pKa > pH, otherwise it returns a deprotonated state of the first form.

Then, is it weird to have a `Chem.CanonSmiles(smi)` of each state from the sequence and loop it before returning the value of the `__protonate_pkasolver()`?

> However, there were strange protonated forms like protonated amide groups, which are fixed before return the output. If there are some other typical errors, we may create a list of patterns to check all of them and fix.

Yes, that can be done if there are patterns of the input smiles

> Not an easy question for me, because I'm not familiar with GPU support in Python and torch. This should be investigated whether it is possible to switch between CPU and GPU modes through API. If so, then we can introduce an additional ngpu argument, which will be None by default and which can be set by a user independently on ncpu.

Sure, I can test to see if the torch-gpu can use cpu without needing to reinstall two different versions of pytorch. If that is possible, then I may have to edit the pkasolver `query` function to use CPU and GPU depending on the `protonate_pkasolver() ` argument

**Comment by Feriolet** [comment]
It seems that torch-gpu can use cpu as well, provided that the `torch.device` is set to "cpu" in `pkasolver.query` script. However, a surprising thing is that I found that using CPU is actually faster to protonate the molecules compared to GPU. When I used `maxtasksperchild=1` and `chunksize=50` for default multiprocessing, the expected protonation time came up to be ~20 minutes for 50k compound from tqdm. I think the reason why it takes so slow previously with CPU is that the `chunksize=1` by default.  I am currently trying to protonate the whole 600k again, and if the time taken is significantly lesser than using GPU, we can stick to default `multiprocessing` and we do not need to use GPU for pkasolver.

**Comment by Feriolet** [comment]
Protonation result:
GPU 10 threads, maxtasksperchild=1, `chunksize=50` -> protonation done in 78914.76s
CPU 150, no maxtasksperchild specified, `chunksize=500` -> protonation done in 5104.00s

Although the CPU has a higher chunksize than GPU, I still think that this means we can just use CPU instead of GPU, which makes it easier to maintain the protonation function. We just need to specify a high number of chunksize to speed up the pkasolver protonation.

**Comment by DrrDom** [comment]
Thank you for the study. I agree with your suggestion to increase the chunk size. It can be done dynamically, you may roughly estimate the chunk size from the size of the input file. One SMILES with ID takes about 60-80 bytes, so we may divide the file size on 70 to get a total number of compounds in a file and set chunksize to `min(max(0, nsmi / ncpu), 500)`. This will return the value within the range 1-500.
